const SPACE_SHIP_DIAMETER = 35;
const SPACE_SHIP_COLOR = "orange";
const SPACE_SHIP_X_SPEED = 2;
const SPACE_SHIP_Y_SPEED = 2;
const SPACE_SHIP_X_START_POSITION = 250;
const SPACE_SHIP_Y_START_POSITION = 450;
const SPACE_SHIP_IMAGE_PATH = "space-ship.png"

const ASTEROID_MAX_COUNT = 5;
const ASTEROID_MIN_DIAMETER = 20;
const ASTEROID_MAX_DIAMETER = 40;
const ASTEROID_COLOR = " white";
const ASTEROID_MIN_X_SPEED = 0;
const ASTEROID_MAX_X_SPEED = 0.5;
const ASTEROID_MIN_Y_SPEED = 0.5;
const ASTEROID_MAX_Y_SPEED = 3;
const ASTEROID_MIN_X_SPAWN_POSITION = 0;
const ASTEROID_MAX_X_SPAWN_POSITION = 500;
const ASTEROID_MIN_Y_SPAWN_POSITION = 0;
const ASTEROID_MAX_Y_SPAWN_POSITION = 0;
const ASTEROID_IMAGE_PATH = "asteroid.png";

const STAR_BACKGROUND_IMAGE_PATH = "star-background.png";
const PLAY_ICON_IMAGE_PATH = "play.png";